#server:
#  # -1 代表随机
#  port: 8080
#  servlet:
#    context-path: /backend/
#
#spring:
#  application:
#    name: apihub-backend
#  # DataSource Config
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/apihub #?allowPublicKeyRetrieval=true
#    #    url: jdbc:mysql://localhost:3306/yuapi #?allowPublicKeyRetrieval=true
#    username: root
#    password: 123456
#  #swagger 兼容性配置
#  mvc:
#    pathmatch:
#      matching-strategy: ANT_PATH_MATCHER
#  # session 失效时间（分钟）- 一天
#  session:
#    timeout: 86400
#    # 配置了redis分布式session方案
#    store-type: redis
#  # redis 配置
#  redis:
#    port: 6379
#    host: 111.229.176.89
#    database: 0
#
#mybatis-plus:
#  configuration:
#    map-underscore-to-camel-case: false
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#  global-config:
#    db-config:
#      logic-delete-field: isDelete # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
#      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
#      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
#
#dubbo:
#  application:
#    name: apihub-backend
#  protocol:
#    name: dubbo
#    port: -1
#  registry:
#    id: nacos-registry
#    address: nacos://localhost:8848
#    address: zookeeper://localhost:2181
#  # scan:
#  #   base-packages: com.example.service.impl.inner
#
## 接口文档配置
#knife4j:
#  enable: true
#  openapi:
#    title: apihub后端接口文档
#    # description: "`我是测试`,**你知道吗**"
#    # email: xiaoymin@foxmail.com
#    version: v1.0
#    group:
#      default:
#        group-name: 分组名称
#        api-rule: package
#        api-rule-resources:
#          - com.example.controller    #这个应该和包路径保持一致